name: Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Sphinx packages
        run: |
          pip install sphinx sphinx-design pydata-sphinx-theme \
                      myst-parser linkify-it-py
      - name: build docs
        run: |
          cd docs
          make clean html
          cd ../
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.13.x
          lhci autorun --config=.github/lighthouserc.yml